# Generated by Django 5.1.4 on 2024-12-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=200)),
                ('date_sent', models.DateTimeField()),
                ('date_received', models.DateTimeField()),
            ],
        ),
    ]
