# Generated by Django 5.1.4 on 2024-12-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecapsule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='emotion',
            field=models.CharField(choices=[('joy', 'joy'), ('sad', 'sadness'), ('ang', 'anger'), ('sur', 'surprise')], default='joy', max_length=3),
        ),
    ]
