# Generated by Django 5.1.4 on 2024-12-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecapsule', '0002_message_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='emotion',
            field=models.CharField(max_length=8),
        ),
    ]
